# SlidingBlockAnalysis { #pyslammer.SlidingBlockAnalysis }

```python
SlidingBlockAnalysis(
    ky,
    ground_motion,
    scale_factor=1.0,
    target_pga=None,
    inverse=False,
)
```

Base class for all time-domain sliding block analyses. `SlidingBlockAnalysis` does not
perform any analysis by itself. It is meant to be subclassed by other classes that
implement specific sliding block analysis methods.
It performs checks on the input parameters and initializes the attributes for the analysis.
The class also provides a method to plot the results of the analysis.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type                 | Description                                                                                                                                                                              | Default    |
|---------------|----------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| ky            | float                | Yield acceleration of the sliding block (in g).                                                                                                                                          | _required_ |
| ground_motion | GroundMotion or dict | Ground motion data. Can be: - A GroundMotion object - A dictionary with keys: 'accel', 'dt', and optionally 'name'   Example: {'accel': [0.1, 0.2, 0.1], 'dt': 0.01, 'name': 'MyMotion'} | _required_ |
| scale_factor  | float                | Scaling factor for the input acceleration. Default is 1.0.                                                                                                                               | `1.0`      |
| target_pga    | float                | Target peak ground acceleration (in g). If provided, the input acceleration will be scaled to match this value. Cannot be used with `scale_factor`.                                      | `None`     |
| inverse       | bool                 | If True, inverts the direction of the ground motion by negating the scale factor. This is equivalent to running the analysis in the "inverse" direction. Default is False.               | `False`    |

## Raises {.doc-section .doc-section-raises}

| Name   | Type       | Description                                           |
|--------|------------|-------------------------------------------------------|
|        | ValueError | If both `target_pga` and `scale_factor` are provided. |

## Attributes {.doc-section .doc-section-attributes}

| Name             | Type                  | Description                                                        |
|------------------|-----------------------|--------------------------------------------------------------------|
| scale_factor     | float                 | Scaling factor applied to the input acceleration.                  |
| a_in             | numpy.ndarray         | Scaled input acceleration time series.                             |
| dt               | float                 | Time step of the input acceleration time series (in seconds).      |
| motion_name      | str                   | Name of the ground motion record.                                  |
| method           | str or None           | Analysis method used (to be defined in subclasses).                |
| ky               | float or None         | Yield acceleration of the sliding block (in g) for user interface. |
| _ky_             | float or None         | Internal yield acceleration (in m/s^2) for calculations.           |
| time             | numpy.ndarray or None | Time array corresponding to the input acceleration.                |
| _ground_acc_     | numpy.ndarray or None | Internal ground acceleration time series (in m/s^2).               |
| ground_vel       | numpy.ndarray or None | Ground velocity time series (in m/s).                              |
| ground_disp      | numpy.ndarray or None | Ground displacement time series (in m).                            |
| block_acc        | numpy.ndarray or None | Block acceleration time series (in m/s^2).                         |
| block_vel        | numpy.ndarray or None | Block velocity time series (in m/s).                               |
| block_disp       | numpy.ndarray or None | Block displacement time series (in m).                             |
| sliding_vel      | numpy.ndarray or None | Sliding velocity time series (in m/s).                             |
| sliding_disp     | numpy.ndarray or None | Sliding displacement time series (in m).                           |
| max_sliding_disp | float or None         | Maximum sliding displacement (in m).                               |
| _npts            | int or None           | Number of points in the input acceleration time series.            |

## Methods

| Name | Description |
| --- | --- |
| [sliding_block_plot](#pyslammer.SlidingBlockAnalysis.sliding_block_plot) | Plot the analysis result as a 3-by-1 array of time series figures. |

### sliding_block_plot { #pyslammer.SlidingBlockAnalysis.sliding_block_plot }

```python
SlidingBlockAnalysis.sliding_block_plot(
    time_range=None,
    sliding_vel_mode=True,
    fig=None,
)
```

Plot the analysis result as a 3-by-1 array of time series figures.

#### Parameters {.doc-section .doc-section-parameters}

| Name             | Type                     | Description                                                                                                                                                                     | Default   |
|------------------|--------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| sliding_vel_mode | bool                     | If True, the velocity figure shows the sliding (relative) velocity of the block. If False, it shows the absolute velocities of the input motion and the block. Default is True. | `True`    |
| fig              | matplotlib.figure.Figure | Existing figure to plot on. If None, a new figure is created. Default is None.                                                                                                  | `None`    |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type                     | Description                      |
|--------|--------------------------|----------------------------------|
|        | matplotlib.figure.Figure | The figure containing the plots. |